### ISSUE TITLE
`path.sep` goes missing when importing in a debugger in Python 3.10

### ISSUE THREAD

**Issue by TomTruck** [pyproj4/pyproj#1028]
I've created [a repository](https://github.com/TomTruck/pyproj-sep-debugger) that contains a working example that demonstrates this problem.

#### Code Sample, a copy-pastable example if possible

The problem arises when importing `pyproj` in a debugger.  A minimal example is as follows.

```python
import os

import pyproj

os.path.sep

if __name__ == '__main__':
    pass
```

More details are available in the [repository](https://github.com/TomTruck/pyproj-sep-debugger) README.

#### Problem description

When importing `pyproj` in a debugger the `os.path` module gets modified so that `os.path.sep` raises an `AttributeError`

#### Expected Output

`os.path.sep` returns the same value as before importing `os.path.sep`

#### Environment Information
Run inside a docker container defined as follows:

```dockerfile
FROM python:3.10.2-bullseye@sha256:083f7050ed966b5e430b5c0ebc439af58094ac59f37861573966121652d2d790  AS base

WORKDIR /app

RUN pip install --upgrade pip==21.3.1

RUN curl -sSL https://install.python-poetry.org | python - --yes --version 1.1.12
ENV PATH="/root/.local/bin:$PATH"

RUN poetry config virtualenvs.create false

COPY pyproject.toml .

RUN poetry lock

RUN poetry install --no-interaction
```

Dependencies are defined via Poetry in a `pyproject.toml` file:

```toml
[tool.poetry]
name = "Debug missing sep"
version = "0.1.0"
description = "Routing"
authors = ["Tom Finill"]


[tool.poetry.dependencies]
python = "==3.10.2"
pyproj = "==3.3.0"

```

#### Installation method
 Poetry (see `Dockerfile` above)
